- name: install required packages
  apt:
    pkg:
      - nginx
      - docker.io
      - git
      - curl
      - python3
      - python3-pip
    state: latest
- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: install docker-compose
  pip:
    name: docker-compose
- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
- name: create personal website directory
  file:
    path: /root/personal-website
    state: directory
- name: Log into DockerHub
  docker_login:
    username: {{DOCKER_USERNAME}}
    password: {{DOCKER_PASS}}
- name: template personal website
  template:
    src: ../templates/docker-compose.yml
    dest: /root/personal-website/docker-compose.yml
- name: run personal website
  docker_compose:
    project_src: /root/personal-website
  register: output
- name: template nginx.conf to server
  template:
    src: ../templates/nginx.conf
    dest: /etc/nginx/sites-available/personal-website
- name: activate website
  shell: |
    ln -s /etc/nginx/sites-available/personal-website /etc/nginx/sites-enabled/personal-website
- name: nginx reload signal
  shell: |
    nginx -s reload
